/* 上机实战 · 补充课程（0 基础 C 语言 + 数据结构，追加到 window.LESSONS） */
window.LESSONS = (window.LESSONS || []).concat([
  { id:"z0", chapter:"从0开始", title:"0 基础怎么开始", lang:"c",
    teach:"完全零基础也行，按这个顺序学：\n① 先学本页“C 基础”章节：变量→分支→循环→函数→数组→字符串→指针→结构体。\n② 再看“数据结构上机”章节：顺序表→链表→栈→队列→二叉树→排序→查找→图。\n③ 每节课都：看讲解 → 抄一遍参考代码并运行 → 改一改再运行 → 对答案。\n④ 装个 DevC++(或 VS Code)在本地也能跑；本网站能在线运行。",
    points:"别急，一天吃透 1~2 节就够。写代码 = 抄 + 改 + 自己重写，看会不算会，手敲出来才算。",
    code:'#include <stdio.h>\nint main(){\n    printf("Hello, 我要学会写代码！\\n");\n    return 0;\n}\n',
    stdin:"", output:"Hello, 我要学会写代码！\n" },

  { id:"c-var", chapter:"C 基础", title:"变量与数据类型", lang:"c",
    teach:"常用类型：int(整数4字节)、long long(长整8字节)、float/double(小数)、char(字符1字节)。用 sizeof 看大小。",
    points:"int 约 ±21 亿；更大用 long long(输出 %lld)。printf 格式：%d %lld %f %.2f %c %s。",
    code:'#include <stdio.h>\nint main(){\n    printf("int = %d 字节\\n", (int)sizeof(int));\n    printf("long long = %d 字节\\n", (int)sizeof(long long));\n    printf("double = %d 字节\\n", (int)sizeof(double));\n    return 0;\n}\n',
    stdin:"", output:"int = 4 字节\nlong long = 8 字节\ndouble = 8 字节\n" },

  { id:"c-op", chapter:"C 基础", title:"运算符", lang:"c",
    teach:"算术 + - * / %；整数除法 / 会丢掉小数，% 取余只能用于整数；关系 == != > <；逻辑 && || !；自增 ++。",
    points:"= 是赋值，== 才是相等；(a>b)&&(b>0) 结果为 1(真)或 0(假)。",
    code:'#include <stdio.h>\nint main(){\n    int a = 7, b = 2;\n    printf("a/b=%d a%%b=%d a*b=%d\\n", a / b, a % b, a * b);\n    printf("(a>b)&&(b>0) = %d\\n", (a > b) && (b > 0));\n    return 0;\n}\n',
    stdin:"", output:"a/b=3 a%b=1 a*b=14\n(a>b)&&(b>0) = 1\n" },

  { id:"c-if", chapter:"C 基础", title:"分支：if / switch", lang:"c",
    teach:"if(条件){...} else if(...){...} else {...}。多分支也可用 switch-case(注意 break)。",
    points:"条件要写清范围用 && 连接，如 s>=60 && s<90。",
    code:'#include <stdio.h>\nint main(){\n    int s;\n    scanf("%d", &s);\n    if(s >= 90) printf("优秀\\n");\n    else if(s >= 60) printf("及格\\n");\n    else printf("不及格\\n");\n    return 0;\n}\n',
    stdin:"75\n", output:"及格\n" },

  { id:"c-loop", chapter:"C 基础", title:"循环：for / while", lang:"c",
    teach:"for(初始化; 条件; 步进){...}；while(条件){...}；do{...}while(条件)。break 跳出循环，continue 跳过本次。",
    points:"i 从 0 开始、i<n 是数组/循环的标准写法。",
    code:'#include <stdio.h>\nint main(){\n    int n, i, sum = 0;\n    scanf("%d", &n);\n    for(i = 1; i <= n; i++) sum += i;\n    printf("1..%d 的和 = %d\\n", n, sum);\n    printf("偶数:");\n    for(i = 1; i <= n; i++){ if(i % 2) continue; printf(" %d", i); }\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"6\n", output:"1..6 的和 = 21\n偶数: 2 4 6\n" },

  { id:"c-func", chapter:"C 基础", title:"函数", lang:"c",
    teach:"返回类型 函数名(参数){ 返回 return; }。函数让代码复用、更清晰。C 的参数是“值传递”，想改实参要传指针。",
    points:"函数要先定义或先声明再使用。",
    code:'#include <stdio.h>\nint add(int a, int b){ return a + b; }\nint max2(int a, int b){ return a > b ? a : b; }\nint main(){\n    int x, y;\n    scanf("%d %d", &x, &y);\n    printf("add=%d max=%d\\n", add(x, y), max2(x, y));\n    return 0;\n}\n',
    stdin:"3 8\n", output:"add=11 max=8\n" },

  { id:"c-arr", chapter:"C 基础", title:"一维数组", lang:"c",
    teach:"类型 名[大小]；下标从 0 到 大小-1。用循环批量读写。",
    points:"越界访问(下标 ≥ 大小)会读到别的内存，可能段错误。",
    code:'#include <stdio.h>\nint main(){\n    int n, i, a[100];\n    scanf("%d", &n);\n    for(i = 0; i < n; i++) scanf("%d", &a[i]);\n    printf("逆序: ");\n    for(i = n - 1; i >= 0; i--) printf("%d ", a[i]);\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"4\n1 2 3 4\n", output:"逆序: 4 3 2 1 \n" },

  { id:"c-arr2", chapter:"C 基础", title:"二维数组", lang:"c",
    teach:"a[i][j] 存第 i 行第 j 列；内存里按行连续存放。用双层循环处理。",
    points:"scanf 到二维数组同样要 &a[i][j]。",
    code:'#include <stdio.h>\nint main(){\n    int n, m, i, j, a[10][10];\n    scanf("%d %d", &n, &m);\n    for(i = 0; i < n; i++) for(j = 0; j < m; j++) scanf("%d", &a[i][j]);\n    for(i = 0; i < n; i++){ int s = 0; for(j = 0; j < m; j++) s += a[i][j]; printf("行%d和=%d\\n", i, s); }\n    return 0;\n}\n',
    stdin:"2 3\n1 2 3\n4 5 6\n", output:"行0和=6\n行1和=15\n" },

  { id:"c-str", chapter:"C 基础", title:"字符与字符串", lang:"c",
    teach:"字符串是 char 数组，末尾有 '\\0'。strlen 求长度、strcmp 比较、strcpy 复制(需 #include <string.h>)。%s 读不含空格的串。",
    points:"字符用单引号 'a'，字符串用双引号 \"abc\"。",
    code:'#include <stdio.h>\n#include <string.h>\nint main(){\n    char s[100];\n    int i, n, v = 0;\n    scanf("%s", s);\n    n = strlen(s);\n    for(i = 0; i < n; i++){\n        char c = s[i];\n        if(c==\'a\'||c==\'e\'||c==\'i\'||c==\'o\'||c==\'u\'||c==\'A\'||c==\'E\'||c==\'I\'||c==\'O\'||c==\'U\') v++;\n    }\n    printf("长度=%d 元音=%d\\n", n, v);\n    return 0;\n}\n',
    stdin:"hello\n", output:"长度=5 元音=2\n" },

  { id:"c-ptr", chapter:"C 基础", title:"指针基础", lang:"c",
    teach:"指针存放“地址”。*p 取出 p 指向的值；&x 取变量 x 的地址。int *p = &x; 则 *p 就是 x。",
    points:"指针是 C 的难点也是精髓；考试与数据结构都离不开它。",
    code:'#include <stdio.h>\nint main(){\n    int x = 10;\n    int *p = &x;\n    *p = 20;           /* 通过指针改 x */\n    printf("x = %d\\n", x);\n    return 0;\n}\n',
    stdin:"", output:"x = 20\n" },

  { id:"c-ptrarr", chapter:"C 基础", title:"指针与数组", lang:"c",
    teach:"数组名本质上是指向首元素的指针，a[i] 等价于 *(a+i)。可以用指针遍历数组。",
    points:"for(p=a; p<a+n; p++) 是常见的指针遍历写法。",
    code:'#include <stdio.h>\nint main(){\n    int n, i, a[100], sum = 0, *p;\n    scanf("%d", &n);\n    for(i = 0; i < n; i++) scanf("%d", &a[i]);\n    for(p = a; p < a + n; p++) sum += *p;\n    printf("sum = %d\\n", sum);\n    return 0;\n}\n',
    stdin:"3\n4 5 6\n", output:"sum = 15\n" },

  { id:"c-struct", chapter:"C 基础", title:"结构体", lang:"c",
    teach:"struct 把多个字段打包；typedef 起别名后可直接当类型用。用 . 访问成员，用指针时用 ->。",
    points:"结构体是组织数据(如学生、链表结点)的基础。",
    code:'#include <stdio.h>\ntypedef struct { int x, y; } Point;\nint main(){\n    Point p;\n    Point *q = &p;\n    q->x = 3; q->y = 5;\n    printf("(%d,%d)\\n", p.x, p.y);\n    return 0;\n}\n',
    stdin:"", output:"(3,5)\n" },

  { id:"c-rec", chapter:"C 基础", title:"递归", lang:"c",
    teach:"函数自己调用自己，必须有“终止条件”，否则无限递归崩溃。经典：阶乘、斐波那契、二叉树遍历。",
    points:"先写终止条件(如 n<=1 return)，再写递归式。",
    code:'#include <stdio.h>\nlong long fact(int n){ if(n <= 1) return 1; return n * fact(n - 1); }\nint main(){\n    int n;\n    scanf("%d", &n);\n    printf("%lld\\n", fact(n));\n    return 0;\n}\n',
    stdin:"5\n", output:"120\n" },

  { id:"c-err", chapter:"C 基础", title:"常见错误与调试", lang:"c",
    teach:"三类错误：①编译错误(语法，如少了分号/括号)；②运行时错误/段错误(数组越界、野指针、除 0)；③答案错误(逻辑或格式：多/少空格换行、精度)。调试：看报错行、加 printf 打印中间值。",
    points:"段错误 90% 是数组越界或用了未初始化的指针。",
    code:'#include <stdio.h>\nint main(){\n    int a[5] = {0};\n    int i;\n    for(i = 0; i < 5; i++) a[i] = i * i;   /* i<5 才对；写 i<=5 就越界 */\n    printf("%d\\n", a[4]);\n    return 0;\n}\n',
    stdin:"", output:"16\n" },

  { id:"ds-seq", chapter:"数据结构上机", title:"顺序表：按值查找与删除", lang:"c",
    teach:"顺序表=数组+长度。按值查找 O(n)；删除要把它后面的元素整体前移，长度减 1。",
    points:"先找到位置，再前移覆盖；删除后 n--。",
    code:'#include <stdio.h>\nint main(){\n    int a[100], n, i, x, k = -1;\n    scanf("%d", &n);\n    for(i = 0; i < n; i++) scanf("%d", &a[i]);\n    scanf("%d", &x);\n    for(i = 0; i < n; i++) if(a[i] == x){ k = i; break; }\n    if(k < 0){ printf("没找到\\n"); return 0; }\n    for(i = k; i < n - 1; i++) a[i] = a[i + 1];\n    n--;\n    printf("删除后: ");\n    for(i = 0; i < n; i++) printf("%d ", a[i]);\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"5\n1 2 3 4 5\n3\n", output:"删除后: 1 2 4 5 \n" },

  { id:"ds-dlist", chapter:"数据结构上机", title:"双向链表", lang:"c",
    teach:"每个结点有 prior(前驱)和 next(后继)两个指针；插入/删除要同时改两个方向，更方便反向操作。",
    points:"头插时：p->next=head; if(head) head->prior=p; head=p;",
    code:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct DNode{ int data; struct DNode *prior, *next; } DNode;\nint main(){\n    int n, i, x;\n    DNode *head = NULL, *p;\n    scanf("%d", &n);\n    for(i = 0; i < n; i++){\n        scanf("%d", &x);\n        p = (DNode*)malloc(sizeof(DNode));\n        p->data = x; p->prior = NULL; p->next = head;\n        if(head) head->prior = p;\n        head = p;\n    }\n    printf("正向: ");\n    for(p = head; p; p = p->next) printf("%d ", p->data);\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"4\n1 2 3 4\n", output:"正向: 4 3 2 1 \n" },

  { id:"ds-lstack", chapter:"数据结构上机", title:"链式栈", lang:"c",
    teach:"用单链表实现栈：表头就是栈顶，入栈=头插，出栈=删头，都是 O(1)。",
    points:"top 为 NULL 表示空栈。",
    code:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct SNode{ int data; struct SNode *next; } SNode;\nSNode* push(SNode *top, int v){ SNode *p = (SNode*)malloc(sizeof(SNode)); p->data = v; p->next = top; return p; }\nint main(){\n    int n, i, x;\n    SNode *top = NULL;\n    scanf("%d", &n);\n    for(i = 0; i < n; i++){ scanf("%d", &x); top = push(top, x); }\n    printf("出栈: ");\n    while(top){ printf("%d ", top->data); top = top->next; }\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"4\n1 2 3 4\n", output:"出栈: 4 3 2 1 \n" },

  { id:"ds-lqueue", chapter:"数据结构上机", title:"链式队列", lang:"c",
    teach:"链队列用 front、rear 两个指针：入队尾插到 rear，出队删除 front。",
    points:"空队列时 front=rear=NULL；入第一个元素时 front、rear 都指向它。",
    code:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct QNode{ int data; struct QNode *next; } QNode;\nint main(){\n    int n, i, x;\n    QNode *front = NULL, *rear = NULL, *p;\n    scanf("%d", &n);\n    for(i = 0; i < n; i++){\n        scanf("%d", &x);\n        p = (QNode*)malloc(sizeof(QNode)); p->data = x; p->next = NULL;\n        if(!rear){ front = rear = p; } else { rear->next = p; rear = p; }\n    }\n    printf("出队: ");\n    while(front){ printf("%d ", front->data); front = front->next; }\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"4\n1 2 3 4\n", output:"出队: 1 2 3 4 \n" },

  { id:"ds-tree2", chapter:"数据结构上机", title:"二叉树：叶子数与深度", lang:"c",
    teach:"先序序列(#空)递归建树；叶子数=左右都空的结点数；深度=左右子树深度较大者+1。都用递归。",
    points:"leaves/depth 都是典型递归。",
    code:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct T{ char c; struct T *l, *r; } T;\nT* build(){ char ch; scanf(" %c", &ch); if(ch == \'#\') return NULL;\n    T* t = (T*)malloc(sizeof(T)); t->c = ch; t->l = build(); t->r = build(); return t; }\nint leaves(T* t){ if(!t) return 0; if(!t->l && !t->r) return 1; return leaves(t->l) + leaves(t->r); }\nint depth(T* t){ if(!t) return 0; int a = depth(t->l), b = depth(t->r); return 1 + (a > b ? a : b); }\nint main(){ T* root = build(); printf("叶子数=%d 深度=%d\\n", leaves(root), depth(root)); return 0; }\n',
    stdin:"AB#D##C##\n", output:"叶子数=2 深度=3\n" },

  { id:"ds-level", chapter:"数据结构上机", title:"二叉树：层序遍历", lang:"c",
    teach:"层序遍历用“队列”：根入队，然后每次出队一个结点、打印它、把它左右孩子入队。",
    points:"BFS 思想，靠队列逐层。",
    code:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct T{ char c; struct T *l, *r; } T;\nT* build(){ char ch; scanf(" %c", &ch); if(ch == \'#\') return NULL;\n    T* t = (T*)malloc(sizeof(T)); t->c = ch; t->l = build(); t->r = build(); return t; }\nint main(){\n    T* q[100]; int f = 0, r = 0;\n    T* root = build(); q[r++] = root;\n    printf("层序: ");\n    while(f < r){ T* t = q[f++]; printf("%c ", t->c); if(t->l) q[r++] = t->l; if(t->r) q[r++] = t->r; }\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"AB#D##C##\n", output:"层序: A B C D \n" },

  { id:"ds-sort2", chapter:"数据结构上机", title:"选择排序与插入排序", lang:"c",
    teach:"简单选择：每趟从未排序区选最小放到前面；直接插入：把当前元素插到前面已排好的有序区。都 O(n²)。",
    points:"插入排序在基本有序时很快；选择排序移动次数少。",
    code:'#include <stdio.h>\nvoid sel(int a[], int n){ int i, j, m, t; for(i=0;i<n-1;i++){ m=i; for(j=i+1;j<n;j++) if(a[j]<a[m]) m=j; if(m!=i){t=a[i];a[i]=a[m];a[m]=t;} } }\nvoid ins(int a[], int n){ int i, j, t; for(i=1;i<n;i++){ t=a[i]; j=i-1; while(j>=0&&a[j]>t){ a[j+1]=a[j]; j--; } a[j+1]=t; } }\nvoid show(int a[], int n){ int i; for(i=0;i<n;i++) printf("%d ", a[i]); printf("\\n"); }\nint main(){ int a[100],b[100],n,i; scanf("%d",&n); for(i=0;i<n;i++){ scanf("%d",&a[i]); b[i]=a[i]; }\n    sel(a,n); printf("选择: "); show(a,n);\n    ins(b,n); printf("插入: "); show(b,n);\n    return 0; }\n',
    stdin:"6\n5 2 8 1 9 3\n", output:"选择: 1 2 3 5 8 9 \n插入: 1 2 3 5 8 9 \n" },

  { id:"ds-merge", chapter:"数据结构上机", title:"归并排序", lang:"c",
    teach:"分治：把数组一分为二分别排序，再合并两个有序段。时间 O(nlogn)，需要 O(n) 辅助数组。",
    points:"先递归左右，再“合并”两个有序区间。",
    code:'#include <stdio.h>\nint t[100];\nvoid ms(int a[], int l, int r){\n    if(l >= r) return;\n    int m = (l + r) / 2, i = l, j = m + 1, k = l;\n    ms(a, l, m); ms(a, m + 1, r);\n    while(i <= m && j <= r) t[k++] = (a[i] <= a[j]) ? a[i++] : a[j++];\n    while(i <= m) t[k++] = a[i++];\n    while(j <= r) t[k++] = a[j++];\n    for(i = l; i <= r; i++) a[i] = t[i];\n}\nint main(){ int a[100], n, i; scanf("%d", &n); for(i = 0; i < n; i++) scanf("%d", &a[i]);\n    ms(a, 0, n - 1); for(i = 0; i < n; i++) printf("%d ", a[i]); printf("\\n"); return 0; }\n',
    stdin:"6\n5 2 8 1 9 3\n", output:"1 2 3 5 8 9 \n" },

  { id:"ds-hash", chapter:"数据结构上机", title:"哈希表（除留余数 + 线性探测）", lang:"c",
    teach:"哈希函数 hash(key)=key % M；发生冲突时用“线性探测”找下一个空位：(h+1)%M。查找时按同样规则找。",
    points:"装填因子越高越容易冲突；-1 表示空位。",
    code:'#include <stdio.h>\nint main(){\n    int m, n, i, x, h, t[100];\n    scanf("%d %d", &m, &n);            /* 表长 m, 元素 n */\n    for(i = 0; i < m; i++) t[i] = -1;\n    for(i = 0; i < n; i++){\n        scanf("%d", &x);\n        h = x % m;\n        while(t[h] != -1) h = (h + 1) % m;   /* 线性探测 */\n        t[h] = x;\n    }\n    for(i = 0; i < m; i++) printf("%d ", t[i]);\n    printf("\\n");\n    return 0;\n}\n',
    stdin:"7 5\n8 1 15 22 3\n", output:"-1 8 1 15 22 3 -1 \n" },

  { id:"ds-graphlist", chapter:"数据结构上机", title:"图的邻接表表示", lang:"c",
    teach:"邻接表用“头结点数组 + 边链表”存储每个顶点的邻接点，省空间，适合稀疏图。",
    points:"无向图一条边要存两次(两个方向)。",
    code:'#include <stdio.h>\n#include <stdlib.h>\ntypedef struct E{ int to; struct E *next; } E;\nint main(){\n    int n, m, i, u, v;\n    E *head[50] = {0}, *p;\n    scanf("%d %d", &n, &m);                 /* n 顶点, m 边 */\n    for(i = 0; i < m; i++){\n        scanf("%d %d", &u, &v);\n        p = (E*)malloc(sizeof(E)); p->to = v; p->next = head[u]; head[u] = p;\n        p = (E*)malloc(sizeof(E)); p->to = u; p->next = head[v]; head[v] = p;\n    }\n    for(i = 0; i < n; i++){ printf("%d:", i); for(p = head[i]; p; p = p->next) printf(" %d", p->to); printf("\\n"); }\n    return 0;\n}\n',
    stdin:"3 3\n0 1\n1 2\n0 2\n", output:"0: 2 1\n1: 2 0\n2: 0 1\n" },
]);
